# Generated by Django 5.1.4 on 2024-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_detail', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_image/')),
            ],
        ),
    ]
